//! Benchmark orchestration for pinned Stim and Stab benchmark contracts.

#![cfg_attr(
    test,
    allow(
        clippy::expect_used,
        clippy::unwrap_used,
        reason = "unit tests use direct assertions for compact diagnostics"
    )
)]

mod allocations;
mod baseline;
mod beta_gate;
mod comparability;
mod compare;
mod compare_evidence;
mod config;
mod error;
mod manifest;
mod memory_gate;
mod process;
#[cfg(test)]
mod profile_evidence;
mod qualification;
mod regression_waivers;
mod report;
mod root;
mod source_file;
mod stim;
mod thresholds;

use std::path::PathBuf;
use std::process::ExitCode;

use baseline::{BaselineOptions, run_baseline};
use clap::{Parser, Subcommand};
use compare::{CompareOptions, run_compare};
use config::{DEFAULT_BASELINE_DIR, DEFAULT_BASELINE_REPORT, DEFAULT_STIM_PATH, PREFIX};
use error::BenchError;
use manifest::BenchmarkManifest;
use root::RepoRoot;

#[derive(Debug, Parser)]
#[command(
    about = "Runs Stab benchmark contract and baseline workflows.",
    long_about = "Validates benchmark contracts, builds pinned C++ Stim benchmark targets, records baseline results, and reports planned Stab-vs-Stim comparisons."
)]
struct Cli {
    /// Repository root containing Cargo.toml and vendor/stim.
    #[arg(long, default_value = ".")]
    root: PathBuf,

    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Internal bounded worker used by the paired qualification controller.
    #[command(name = "qualification-worker", hide = true)]
    QualificationWorker(qualification::WorkerArgs),

    /// Print planned benchmark contracts grouped by milestone and threshold.
    List {
        /// Restrict output to one milestone such as M8.
        #[arg(long)]
        milestone: Option<String>,
    },

    /// Validate benchmark contracts without running long benchmark workloads.
    Smoke,

    /// Validate the comprehensive performance qualification ledger.
    QualificationCheck,

    /// List performance qualification coverage and unresolved classifications.
    QualificationList {
        /// Restrict output to an exact PERF-* feature id.
        #[arg(long)]
        feature: Option<String>,
    },

    /// Regenerate or compare the deterministic performance qualification ledger.
    QualificationRegenerate {
        /// Compare generated bytes with the checked inventory instead of writing it.
        #[arg(long)]
        check: bool,
    },

    /// Regenerate or check the frozen Clifford-string qualification vectors.
    #[command(hide = true)]
    QualificationCliffordVectors {
        /// Compare generated bytes with the checked vectors instead of writing them.
        #[arg(long)]
        check: bool,
    },

    /// Reproduce one bounded runner or product-adapter probe.
    QualificationProbe(qualification::ProbeArgs),

    /// Require two isolated private builds to produce identical worker binaries.
    QualificationWorkerReproducibility,

    /// Run one paired qualification group and publish validated evidence.
    QualificationRun(qualification::RunArgs),

    /// Validate a paired qualification report and regenerate derived artifacts.
    QualificationReport(qualification::ReportArgs),

    /// Execute and bind every machine-checkable milestone closure operation.
    QualificationCompletion(qualification::CompletionArgs),

    /// Replay a milestone completion receipt from its exact source evidence.
    QualificationCompletionReport(qualification::CompletionReportArgs),

    /// Check promotable qualification evidence against source-owned thresholds.
    QualificationRegression(qualification::RegressionArgs),

    /// Bind one complete architecture-scoped scale family into a rollup.
    QualificationRollup(qualification::RollupArgs),

    /// Replay a scale-family rollup from its exact source reports.
    QualificationRollupReport(qualification::RollupReportArgs),

    /// Record pinned C++ Stim baseline benchmark results.
    Baseline {
        /// Path to the pinned Stim source checkout.
        #[arg(long, default_value = DEFAULT_STIM_PATH)]
        stim: PathBuf,

        /// Directory receiving baseline.json and report.md.
        #[arg(long, default_value = DEFAULT_BASELINE_DIR)]
        out: PathBuf,

        /// Target seconds passed to Stim's stim_perf harness for each filter.
        #[arg(long, default_value_t = 0.01)]
        target_seconds: f64,

        /// Number of process launches for Stim CLI benchmark rows.
        #[arg(long, default_value_t = 3)]
        cli_iterations: u32,

        /// Run only rows whose id or milestone matches this value.
        #[arg(long = "only")]
        only: Vec<String>,

        /// Record only the frozen M12 primary matrix.
        #[arg(long)]
        primary: bool,

        /// Force reconfiguration and rebuild of the pinned Stim benchmark binaries.
        #[arg(long)]
        rebuild_stim: bool,
    },

    /// Report planned Stab-vs-Stim benchmark comparisons.
    Compare {
        /// Restrict comparison planning to one milestone such as M8.
        #[arg(long)]
        milestone: Option<String>,

        /// Run the benchmark comparison under the named Cargo profile.
        #[arg(long, default_value = "release")]
        profile: String,

        /// Compare the frozen M12 primary matrix instead of every manifest row.
        #[arg(long)]
        primary: bool,

        /// Run only rows whose id or milestone matches this value.
        #[arg(long = "only")]
        only: Vec<String>,

        /// Baseline JSON report produced by `bench::baseline`.
        #[arg(long, default_value = DEFAULT_BASELINE_REPORT)]
        baseline: PathBuf,

        /// Directory receiving compare.json and report.md.
        #[arg(long)]
        report: Option<PathBuf>,

        /// Fail when rows slower than the hot-path threshold do not have valid profiler notes beside the report.
        #[arg(long)]
        require_profiler_notes: bool,

        /// Directory containing profiler notes, defaulting to `report/profiler-notes`.
        #[arg(long)]
        profiler_notes_dir: Option<PathBuf>,

        /// Fail when selected rows do not prove the 1.25x beta performance gate.
        #[arg(long)]
        require_beta_gate: bool,

        /// JSON waiver file for measured contract-only rows that cannot prove a pinned-Stim ratio.
        #[arg(long)]
        beta_waivers: Option<PathBuf>,

        /// Fail when Stab allocation bytes regress more than the M12 beta memory budget.
        #[arg(long)]
        require_memory_gate: bool,

        /// Compare report from the first complete Stab allocation run used by the memory gate.
        #[arg(long)]
        memory_baseline: Option<PathBuf>,

        /// JSON regression threshold file checked against selected benchmark rows.
        #[arg(long)]
        thresholds: Option<PathBuf>,

        /// JSON waiver file for measured contract-only rows with no faithful regression ratio.
        #[arg(long)]
        regression_waivers: Option<PathBuf>,

        /// Measure Stab-side allocation counts using the count-allocations feature.
        #[arg(long)]
        track_allocations: bool,

        /// Run selected Stab-side compare workloads once before recording report measurements.
        #[arg(long)]
        warmup: bool,

        /// Number of recorded Stab-side measurement runs per selected row.
        #[arg(long, default_value_t = 1)]
        measurement_runs: usize,

        /// Exit with an error while Stab benchmark comparison runners are pending.
        #[arg(long)]
        strict: bool,
    },
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    match run(cli) {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("[{PREFIX}] ERROR: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run(cli: Cli) -> Result<(), BenchError> {
    let Cli { root, command } = cli;
    let command = match command {
        Command::QualificationWorker(args) => return qualification::run_worker(args),
        command => command,
    };
    let root = RepoRoot::resolve(&root)?;
    match command {
        Command::QualificationWorker(_) => {
            return Err(BenchError::Qualification(
                "qualification worker dispatch reached the repository controller".to_string(),
            ));
        }
        Command::List { milestone } => {
            let manifest = checked_manifest(&root)?;
            manifest.list(milestone.as_deref());
        }
        Command::Smoke => {
            let manifest = checked_manifest(&root)?;
            println!(
                "[{PREFIX}] benchmark manifest OK: {} planned rows",
                manifest.rows.len()
            );
        }
        Command::QualificationCheck => {
            let manifest = checked_manifest(&root)?;
            qualification::check(&root, &manifest)?;
        }
        Command::QualificationList { feature } => {
            let manifest = checked_manifest(&root)?;
            qualification::list(&root, &manifest, feature.as_deref())?;
        }
        Command::QualificationRegenerate { check } => {
            let manifest = checked_manifest(&root)?;
            qualification::regenerate(&root, &manifest, check)?;
        }
        Command::QualificationCliffordVectors { check } => {
            qualification::regenerate_clifford_vectors(&root, check)?;
        }
        Command::QualificationProbe(args) => {
            qualification::probe(&root, args)?;
        }
        Command::QualificationWorkerReproducibility => {
            qualification::worker_reproducibility(&root)?;
        }
        Command::QualificationRun(args) => {
            qualification::run_qualification(&root, args)?;
        }
        Command::QualificationReport(args) => {
            qualification::report(&root, args)?;
        }
        Command::QualificationCompletion(args) => {
            qualification::completion(&root, args)?;
        }
        Command::QualificationCompletionReport(args) => {
            qualification::completion_report(&root, args)?;
        }
        Command::QualificationRegression(args) => {
            qualification::regression(&root, args)?;
        }
        Command::QualificationRollup(args) => {
            qualification::rollup(&root, args)?;
        }
        Command::QualificationRollupReport(args) => {
            qualification::rollup_report(&root, args)?;
        }
        Command::Baseline {
            stim,
            out,
            target_seconds,
            cli_iterations,
            only,
            primary,
            rebuild_stim,
        } => {
            let manifest = checked_manifest(&root)?;
            run_baseline(
                &root,
                &manifest,
                &BaselineOptions {
                    stim,
                    out,
                    target_seconds,
                    cli_iterations,
                    only,
                    primary,
                    rebuild_stim,
                },
            )?;
        }
        Command::Compare {
            milestone,
            profile,
            primary,
            only,
            baseline,
            report,
            require_profiler_notes,
            profiler_notes_dir,
            require_beta_gate,
            beta_waivers,
            require_memory_gate,
            memory_baseline,
            thresholds,
            regression_waivers,
            track_allocations,
            warmup,
            measurement_runs,
            strict,
        } => {
            let manifest = checked_manifest(&root)?;
            run_compare(
                &root,
                &manifest,
                &CompareOptions {
                    baseline,
                    milestone,
                    profile,
                    primary,
                    only,
                    report,
                    require_profiler_notes,
                    profiler_notes_dir,
                    require_beta_gate,
                    beta_waivers,
                    require_memory_gate,
                    memory_baseline,
                    thresholds,
                    regression_waivers,
                    track_allocations,
                    warmup,
                    measurement_runs,
                    strict,
                },
            )?;
        }
    }
    Ok(())
}

fn checked_manifest(root: &RepoRoot) -> Result<BenchmarkManifest, BenchError> {
    let manifest = BenchmarkManifest::read(root)?;
    manifest.check(root)?;
    Ok(manifest)
}
