//! The static Stim v1.16.0 gate table: one row per gate carrying category,
//! argument and target rules, inverse identity, classification flags, and
//! the accepted alias list. Classification accessors in the parent module
//! derive every view from these rows.

use super::{ArgRule, GateCategory, GateFlags, GateInfo, TargetRule};

const fn gate(
    name: &'static str,
    category: GateCategory,
    arg_rule: ArgRule,
    target_rule: TargetRule,
) -> GateInfo {
    gate_with_inverse(name, name, category, arg_rule, target_rule)
}

const fn gate_with_inverse(
    name: &'static str,
    inverse_name: &'static str,
    category: GateCategory,
    arg_rule: ArgRule,
    target_rule: TargetRule,
) -> GateInfo {
    GateInfo {
        name,
        inverse_name,
        category,
        arg_rule,
        target_rule,
        can_fuse: true,
        flags: GateFlags::NONE,
        aliases: &[],
    }
}

const fn not_fusable_gate(
    name: &'static str,
    category: GateCategory,
    arg_rule: ArgRule,
    target_rule: TargetRule,
) -> GateInfo {
    GateInfo {
        name,
        inverse_name: name,
        category,
        arg_rule,
        target_rule,
        can_fuse: false,
        flags: GateFlags::NONE,
        aliases: &[],
    }
}

pub(super) const GATES: &[GateInfo] = &[
    not_fusable_gate(
        "DETECTOR",
        GateCategory::Annotation,
        ArgRule::Any,
        TargetRule::RecOnly,
    ),
    not_fusable_gate(
        "OBSERVABLE_INCLUDE",
        GateCategory::Annotation,
        ArgRule::UnsignedInteger,
        TargetRule::RecOrPauli,
    ),
    not_fusable_gate(
        "TICK",
        GateCategory::Annotation,
        ArgRule::Exact(0),
        TargetRule::None,
    ),
    not_fusable_gate(
        "QUBIT_COORDS",
        GateCategory::Annotation,
        ArgRule::Any,
        TargetRule::QubitCoords,
    ),
    not_fusable_gate(
        "SHIFT_COORDS",
        GateCategory::Annotation,
        ArgRule::Any,
        TargetRule::None,
    ),
    not_fusable_gate(
        "REPEAT",
        GateCategory::ControlFlow,
        ArgRule::Exact(0),
        TargetRule::None,
    ),
    gate(
        "MPAD",
        GateCategory::Annotation,
        ArgRule::ZeroOrOneProbability,
        TargetRule::MeasurementPads,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS),
    gate(
        "MX",
        GateCategory::Collapsing,
        ArgRule::ZeroOrOneProbability,
        TargetRule::MeasurementQubits,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS),
    gate(
        "MY",
        GateCategory::Collapsing,
        ArgRule::ZeroOrOneProbability,
        TargetRule::MeasurementQubits,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS),
    gate(
        "M",
        GateCategory::Collapsing,
        ArgRule::ZeroOrOneProbability,
        TargetRule::MeasurementQubits,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS)
    .with_aliases(&["M", "MZ"]),
    gate(
        "MRX",
        GateCategory::Collapsing,
        ArgRule::ZeroOrOneProbability,
        TargetRule::MeasurementQubits,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS.union(GateFlags::IS_RESET)),
    gate(
        "MRY",
        GateCategory::Collapsing,
        ArgRule::ZeroOrOneProbability,
        TargetRule::MeasurementQubits,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS.union(GateFlags::IS_RESET)),
    gate(
        "MR",
        GateCategory::Collapsing,
        ArgRule::ZeroOrOneProbability,
        TargetRule::MeasurementQubits,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS.union(GateFlags::IS_RESET))
    .with_aliases(&["MR", "MRZ"]),
    gate_with_inverse(
        "RX",
        "MX",
        GateCategory::Collapsing,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    )
    .with_flags(GateFlags::IS_RESET),
    gate_with_inverse(
        "RY",
        "MY",
        GateCategory::Collapsing,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    )
    .with_flags(GateFlags::IS_RESET),
    gate_with_inverse(
        "R",
        "M",
        GateCategory::Collapsing,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    )
    .with_flags(GateFlags::IS_RESET)
    .with_aliases(&["R", "RZ"]),
    gate(
        "XCX",
        GateCategory::Controlled,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate(
        "XCY",
        GateCategory::Controlled,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    ),
    gate(
        "XCZ",
        GateCategory::Controlled,
        ArgRule::Exact(0),
        TargetRule::ClassicalControlPairs,
    ),
    gate(
        "YCX",
        GateCategory::Controlled,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    ),
    gate(
        "YCY",
        GateCategory::Controlled,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate(
        "YCZ",
        GateCategory::Controlled,
        ArgRule::Exact(0),
        TargetRule::ClassicalControlPairs,
    ),
    gate(
        "CX",
        GateCategory::Controlled,
        ArgRule::Exact(0),
        TargetRule::ClassicalControlPairs,
    )
    .with_aliases(&["CNOT", "CX", "ZCX"]),
    gate(
        "CY",
        GateCategory::Controlled,
        ArgRule::Exact(0),
        TargetRule::ClassicalControlPairs,
    )
    .with_aliases(&["CY", "ZCY"]),
    gate(
        "CZ",
        GateCategory::Controlled,
        ArgRule::Exact(0),
        TargetRule::ClassicalControlPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR)
    .with_aliases(&["CZ", "ZCZ"]),
    gate(
        "H",
        GateCategory::HadamardLike,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    )
    .with_aliases(&["H", "H_XZ"]),
    gate(
        "H_XY",
        GateCategory::HadamardLike,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "H_YZ",
        GateCategory::HadamardLike,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "H_NXY",
        GateCategory::HadamardLike,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "H_NXZ",
        GateCategory::HadamardLike,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "H_NYZ",
        GateCategory::HadamardLike,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "DEPOLARIZE1",
        GateCategory::Noise,
        ArgRule::ProbabilityList(1),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "DEPOLARIZE2",
        GateCategory::Noise,
        ArgRule::ProbabilityList(1),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate(
        "X_ERROR",
        GateCategory::Noise,
        ArgRule::ProbabilityList(1),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "Y_ERROR",
        GateCategory::Noise,
        ArgRule::ProbabilityList(1),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "Z_ERROR",
        GateCategory::Noise,
        ArgRule::ProbabilityList(1),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "I_ERROR",
        GateCategory::Noise,
        ArgRule::AnyProbabilityList,
        TargetRule::AnySingleQubit,
    ),
    gate(
        "II_ERROR",
        GateCategory::Noise,
        ArgRule::AnyProbabilityList,
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate(
        "PAULI_CHANNEL_1",
        GateCategory::Noise,
        ArgRule::ProbabilityList(3),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "PAULI_CHANNEL_2",
        GateCategory::Noise,
        ArgRule::ProbabilityList(15),
        TargetRule::PlainPairs,
    ),
    not_fusable_gate(
        "E",
        GateCategory::Noise,
        ArgRule::ProbabilityList(1),
        TargetRule::PauliList,
    )
    .with_aliases(&["CORRELATED_ERROR", "E"]),
    not_fusable_gate(
        "ELSE_CORRELATED_ERROR",
        GateCategory::Noise,
        ArgRule::ProbabilityList(1),
        TargetRule::PauliList,
    ),
    gate(
        "HERALDED_ERASE",
        GateCategory::HeraldedNoise,
        ArgRule::ProbabilityList(1),
        TargetRule::AnySingleQubit,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS),
    gate(
        "HERALDED_PAULI_CHANNEL_1",
        GateCategory::HeraldedNoise,
        ArgRule::ProbabilityList(4),
        TargetRule::AnySingleQubit,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS),
    gate(
        "I",
        GateCategory::Pauli,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "X",
        GateCategory::Pauli,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "Y",
        GateCategory::Pauli,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate(
        "Z",
        GateCategory::Pauli,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "C_XYZ",
        "C_ZYX",
        GateCategory::Period3,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "C_ZYX",
        "C_XYZ",
        GateCategory::Period3,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "C_NXYZ",
        "C_ZYNX",
        GateCategory::Period3,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "C_XNYZ",
        "C_ZNYX",
        GateCategory::Period3,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "C_XYNZ",
        "C_NZYX",
        GateCategory::Period3,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "C_NZYX",
        "C_XYNZ",
        GateCategory::Period3,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "C_ZNYX",
        "C_XNYZ",
        GateCategory::Period3,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "C_ZYNX",
        "C_NXYZ",
        GateCategory::Period3,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "SQRT_X",
        "SQRT_X_DAG",
        GateCategory::Period4,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "SQRT_X_DAG",
        "SQRT_X",
        GateCategory::Period4,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "SQRT_Y",
        "SQRT_Y_DAG",
        GateCategory::Period4,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "SQRT_Y_DAG",
        "SQRT_Y",
        GateCategory::Period4,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    ),
    gate_with_inverse(
        "S",
        "S_DAG",
        GateCategory::Period4,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    )
    .with_aliases(&["S", "SQRT_Z"]),
    gate_with_inverse(
        "S_DAG",
        "S",
        GateCategory::Period4,
        ArgRule::Exact(0),
        TargetRule::AnySingleQubit,
    )
    .with_aliases(&["S_DAG", "SQRT_Z_DAG"]),
    gate(
        "II",
        GateCategory::ParityPhasing,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate_with_inverse(
        "SQRT_XX",
        "SQRT_XX_DAG",
        GateCategory::ParityPhasing,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate_with_inverse(
        "SQRT_XX_DAG",
        "SQRT_XX",
        GateCategory::ParityPhasing,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate_with_inverse(
        "SQRT_YY",
        "SQRT_YY_DAG",
        GateCategory::ParityPhasing,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate_with_inverse(
        "SQRT_YY_DAG",
        "SQRT_YY",
        GateCategory::ParityPhasing,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate_with_inverse(
        "SQRT_ZZ",
        "SQRT_ZZ_DAG",
        GateCategory::ParityPhasing,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate_with_inverse(
        "SQRT_ZZ_DAG",
        "SQRT_ZZ",
        GateCategory::ParityPhasing,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate(
        "MPP",
        GateCategory::PauliProduct,
        ArgRule::ZeroOrOneProbability,
        TargetRule::PauliProducts,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS),
    gate_with_inverse(
        "SPP",
        "SPP_DAG",
        GateCategory::PauliProduct,
        ArgRule::Exact(0),
        TargetRule::PauliProducts,
    ),
    gate_with_inverse(
        "SPP_DAG",
        "SPP",
        GateCategory::PauliProduct,
        ArgRule::Exact(0),
        TargetRule::PauliProducts,
    ),
    gate(
        "SWAP",
        GateCategory::Swap,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate_with_inverse(
        "ISWAP",
        "ISWAP_DAG",
        GateCategory::Swap,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate_with_inverse(
        "CXSWAP",
        "SWAPCX",
        GateCategory::Swap,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    ),
    gate_with_inverse(
        "SWAPCX",
        "CXSWAP",
        GateCategory::Swap,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    ),
    gate(
        "CZSWAP",
        GateCategory::Swap,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR)
    .with_aliases(&["CZSWAP", "SWAPCZ"]),
    gate_with_inverse(
        "ISWAP_DAG",
        "ISWAP",
        GateCategory::Swap,
        ArgRule::Exact(0),
        TargetRule::PlainPairs,
    )
    .with_flags(GateFlags::SYMMETRIC_PAIR),
    gate(
        "MXX",
        GateCategory::PairMeasurement,
        ArgRule::ZeroOrOneProbability,
        TargetRule::MeasurementPairs,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS.union(GateFlags::SYMMETRIC_PAIR)),
    gate(
        "MYY",
        GateCategory::PairMeasurement,
        ArgRule::ZeroOrOneProbability,
        TargetRule::MeasurementPairs,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS.union(GateFlags::SYMMETRIC_PAIR)),
    gate(
        "MZZ",
        GateCategory::PairMeasurement,
        ArgRule::ZeroOrOneProbability,
        TargetRule::MeasurementPairs,
    )
    .with_flags(GateFlags::PRODUCES_RESULTS.union(GateFlags::SYMMETRIC_PAIR)),
];
