use std::path::Path;

use super::super::{FeatureId, classify_public_api_source};

#[test]
fn extracted_analysis_apis_keep_semantic_feature_ownership() {
    for (crate_name, source, api, expected) in [
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit.rs",
            "stab_analysis::circuit_without_tags",
            FeatureId::CircuitApi,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_simplify.rs",
            "stab_analysis::simplified_circuit",
            FeatureId::CircuitApi,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_tableau.rs",
            "stab_analysis::circuit_to_tableau",
            FeatureId::Algebra,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_transforms.rs",
            "stab_analysis::flattened_circuit",
            FeatureId::CircuitApi,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_transforms.rs",
            "stab_analysis::flattened_circuit_with_limits",
            FeatureId::Resource,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_generation.rs",
            "stab_analysis::generate_surface_code_circuit",
            FeatureId::Generation,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_flow/generators.rs",
            "stab_analysis::circuit_flow_generators",
            FeatureId::FlowUtils,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/sparse_rev_frame_tracker.rs",
            "stab_analysis::advanced::SparseReverseFrameTracker",
            FeatureId::FlowUtils,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_inverse.rs",
            "stab_analysis::InverseQecOptions",
            FeatureId::FlowUtils,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_inverse.rs",
            "stab_analysis::circuit_time_reversed_for_flows",
            FeatureId::FlowUtils,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_feedback.rs",
            "stab_analysis::circuit_with_inlined_feedback",
            FeatureId::FlowUtils,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_detecting_regions.rs",
            "stab_analysis::DetectingRegionOptions",
            FeatureId::FlowUtils,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_missing_detectors.rs",
            "stab_analysis::missing_detectors",
            FeatureId::FlowUtils,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_to_dem.rs",
            "stab_analysis::circuit_to_detector_error_model",
            FeatureId::Analyzer,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/circuit_to_dem/error_decomp.rs",
            "stab_analysis::IndependentPauliProbabilities",
            FeatureId::Analyzer,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/mbqc_decomposition.rs",
            "stab_analysis::mbqc_decomposition",
            FeatureId::CircuitApi,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/resources.rs",
            "stab_analysis::ResourceKind",
            FeatureId::Resource,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/gate.rs",
            "stab_analysis::single_qubit_clifford_for_gate",
            FeatureId::Algebra,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/gate.rs",
            "stab_analysis::gate_tableau",
            FeatureId::GateContract,
        ),
        (
            "stab_analysis",
            "crates/stab-analysis/src/error.rs",
            "stab_analysis::AnalysisError",
            FeatureId::Analyzer,
        ),
        (
            "stab_core",
            "crates/stab-core/src/lib.rs",
            "stab_core::GateUnitaryMatrix",
            FeatureId::GateContract,
        ),
        (
            "stab_core",
            "crates/stab-core/src/lib.rs",
            "stab_core::ColorCodeTask",
            FeatureId::Generation,
        ),
        (
            "stab_core",
            "crates/stab-core/src/lib.rs",
            "stab_core::GeneratedCircuit::layout_text",
            FeatureId::Generation,
        ),
        (
            "stab_core",
            "crates/stab-core/src/lib.rs",
            "stab_core::DisjointPauliProbabilities",
            FeatureId::Analyzer,
        ),
        (
            "stab_core",
            "crates/stab-core/src/dem/analyze.rs",
            "stab_core::try_disjoint_to_independent_xyz_errors",
            FeatureId::Analyzer,
        ),
        (
            "stab_core",
            "crates/stab-core/src/analysis/mod.rs",
            "stab_core::analysis::gate_tableau",
            FeatureId::GateContract,
        ),
        (
            "stab_core",
            "crates/stab-core/src/analysis/mod.rs",
            "stab_core::analysis::single_qubit_clifford_for_gate",
            FeatureId::Algebra,
        ),
        (
            "stab_core",
            "crates/stab-core/src/analysis/mod.rs",
            "stab_core::analysis::circuit_without_tags",
            FeatureId::CircuitApi,
        ),
        (
            "stab_core",
            "crates/stab-core/src/circuit_flow.rs",
            "stab_core::circuit_flow_generators",
            FeatureId::FlowUtils,
        ),
    ] {
        assert_eq!(
            classify_public_api_source(crate_name, Path::new(source), api),
            Some(expected),
            "{api}",
        );
    }
}
