use std::collections::BTreeMap;
use std::path::PathBuf;

use clap::Subcommand;
use thiserror::Error;

use self::model::{EvidenceStatus, FeatureId, QualificationManifest, UpstreamDisposition};
use crate::RepoRoot;
use crate::blocker_ledger::selector::{CargoTestSelector, test_listing_match_count};

pub(crate) mod artifact;
mod artifact_locator;
mod classification;
mod comparator;
pub(crate) mod executables;
mod execution_contract;
mod extract;
mod inventory;
mod model;
mod property;
mod property_validation;
mod public_api;
mod public_api_validation;
mod receipt;
mod report;
mod resource;
mod runner;
mod statistical_validation;
mod statistics;
mod tier;
mod validation;

const EXPECTED_FROZEN_DIGEST: &str =
    "7a0f0fd50bc46221d4c1b489f9bb3d52f0a2e8ced996087f5714c72699645c7b";
const MAX_MANIFEST_BYTES: usize = 32 << 20;
const PROVENANCE_PROBE_CASE_ID: &str = "cq-evidence-oracle-d4836033794f54f7";
const PROVENANCE_PROBE_OUTPUT_DIR: &str = "target/qualification/correctness/provenance-probe";

#[derive(Debug, Subcommand)]
pub(crate) enum Command {
    /// Operate on comprehensive correctness qualification evidence.
    Correctness {
        #[command(subcommand)]
        command: CorrectnessCommand,
    },
}

#[derive(Debug, Subcommand)]
pub(crate) enum CorrectnessCommand {
    /// Validate the source-owned correctness qualification inventory.
    Check,

    /// List correctness qualification coverage by feature and disposition.
    List {
        /// Restrict output to an exact feature id such as CQ-RESULT-FORMATS.
        #[arg(long)]
        feature: Option<String>,
    },

    /// Regenerate or compare the deterministic correctness inventory.
    Regenerate {
        /// Compare generated bytes with the checked-in manifest instead of writing it.
        #[arg(long)]
        check: bool,
    },

    /// Rebuild private tools and validate one real case's complete provenance chain.
    ProvenanceProbe {
        /// Repository-relative diagnostic report directory under target/qualification.
        #[arg(long, default_value = PROVENANCE_PROBE_OUTPUT_DIR)]
        out: PathBuf,
    },

    /// Execute source-owned correctness cases and publish JSON, Markdown, and preflight reports.
    Run {
        /// Qualification tier to execute.
        #[arg(long, value_enum)]
        tier: model::ExecutionTier,

        /// Restrict execution to one or more exact CQ feature ids.
        #[arg(long)]
        feature: Vec<String>,

        /// Restrict execution to one or more exact qualification case ids.
        #[arg(long)]
        case: Vec<String>,

        /// Permit explicitly selected deferred cases to remain visible without execution.
        #[arg(long)]
        allow_deferred: bool,

        /// Repository-relative report directory under target/qualification.
        #[arg(long, default_value = artifact::DEFAULT_OUTPUT_DIR)]
        out: PathBuf,
    },

    /// Validate report JSON and regenerate derived Markdown and preflight indexes.
    Report {
        /// Repository-relative report directory under target/qualification.
        #[arg(long, default_value = artifact::DEFAULT_OUTPUT_DIR)]
        out: PathBuf,
    },

    /// Validate passing correctness prerequisites from a machine-readable report.
    Preflight {
        /// Repository-relative report directory under target/qualification.
        #[arg(long, default_value = artifact::DEFAULT_OUTPUT_DIR)]
        out: PathBuf,

        /// Exact qualification case ids required by the dependent workload.
        #[arg(long, required = true)]
        case: Vec<String>,

        /// Controller-approved digest of request.json for this exact run selection.
        #[arg(long)]
        request_sha256: String,

        /// Controller-approved digest of completion.json for the executed outcomes.
        #[arg(long)]
        completion_sha256: String,

        /// Permit a local report recorded from a modified worktree.
        #[arg(long)]
        allow_dirty: bool,
    },

    /// Execute one qualification adapter inside a killable worker process.
    #[command(hide = true)]
    Worker {
        #[command(subcommand)]
        command: WorkerCommand,
    },
}

#[derive(Debug, Subcommand)]
pub(crate) enum WorkerCommand {
    /// Execute one validated in-process oracle fixture.
    Fixture {
        /// Exact implemented core fixture id.
        #[arg(long)]
        id: String,
    },

    /// Execute one registered property target.
    Property {
        /// Exact registered property target id.
        #[arg(long)]
        id: String,

        /// Source-owned digest of the registered property execution plan.
        #[arg(long)]
        plan_sha256: String,

        /// Dedicated bounded file for a minimized failing regression.
        #[arg(long, conflicts_with = "replay_in")]
        persistence_out: Option<PathBuf>,

        /// Dedicated bounded regression file to replay in this worker.
        #[arg(long, conflicts_with = "persistence_out")]
        replay_in: Option<PathBuf>,
    },
}

#[derive(Debug, Error)]
pub(crate) enum QualificationError {
    #[error(transparent)]
    BlockerLedger(#[from] crate::blocker_ledger::BlockerLedgerError),

    #[error(transparent)]
    Fixture(#[from] crate::fixtures::FixtureError),

    #[error(transparent)]
    Inventory(#[from] inventory::InventoryError),

    #[error(transparent)]
    Validation(#[from] validation::ValidationError),

    #[error(transparent)]
    Run(#[from] runner::RunError),

    #[error(transparent)]
    Report(#[from] report::ReportError),

    #[error(transparent)]
    Receipt(#[from] receipt::ReceiptError),

    #[error(transparent)]
    Artifact(#[from] artifact::ArtifactError),

    #[error("qualification statistics are invalid: {0}")]
    Statistics(Box<str>),

    #[error("qualification worker failed: {0}")]
    Worker(Box<str>),

    #[error("qualification provenance probe failed: {0}")]
    Provenance(Box<str>),

    #[error("failed to read qualification manifest {path}: {reason}")]
    ReadManifest { path: PathBuf, reason: Box<str> },

    #[error("failed to parse qualification manifest {path}: {source}")]
    ParseManifest {
        path: PathBuf,
        source: serde_json::Error,
    },

    #[error("failed to serialize qualification manifest: {0}")]
    SerializeManifest(serde_json::Error),

    #[error("failed to write qualification manifest {path}: {reason}")]
    WriteManifest { path: PathBuf, reason: Box<str> },

    #[error(
        "qualification manifest differs from deterministic pinned-source regeneration; run just qualification::correctness-regenerate"
    )]
    ManifestDrift,

    #[error("unknown qualification feature {0:?}")]
    UnknownFeature(String),

    #[error("qualification inventory is not frozen in source code")]
    UnfrozenDigest,

    #[error("failed to run qualification selector {selector}: {reason}")]
    SelectorProcess { selector: String, reason: Box<str> },

    #[error(
        "qualification selector {selector} exited with {status}\nstdout:\n{stdout}\nstderr:\n{stderr}"
    )]
    SelectorFailed {
        selector: String,
        status: String,
        stdout: Box<str>,
        stderr: Box<str>,
    },

    #[error("qualification selector {selector} matched {actual} tests instead of one")]
    SelectorMatchCount { selector: String, actual: usize },
}

pub(crate) fn run(root: &RepoRoot, command: Command) -> Result<(), QualificationError> {
    let Command::Correctness { command } = command;
    match command {
        CorrectnessCommand::Check => {
            ensure_frozen()?;
            let checked = read_manifest(root)?;
            validation::validate(&checked, EXPECTED_FROZEN_DIGEST)?;
            validate_source_statistics(root)?;
            check_existing_cargo_selectors(root, &checked)?;
            crate::blocker_ledger::validate_and_print(root, false, true)?;
            let generated = inventory::generate(root)?;
            validation::validate(&generated, EXPECTED_FROZEN_DIGEST)?;
            if checked != generated {
                return Err(QualificationError::ManifestDrift);
            }
            print_summary(&checked, None);
        }
        CorrectnessCommand::List { feature } => {
            ensure_frozen()?;
            let selected = feature.as_deref().map(parse_feature).transpose()?;
            let checked = read_manifest(root)?;
            validation::validate(&checked, EXPECTED_FROZEN_DIGEST)?;
            print_summary(&checked, selected);
        }
        CorrectnessCommand::Regenerate { check } => {
            let generated = inventory::generate(root)?;
            validation::validate(
                &generated,
                if check {
                    EXPECTED_FROZEN_DIGEST
                } else {
                    "UNFROZEN"
                },
            )?;
            let bytes = render_manifest(&generated)?;
            if check {
                ensure_frozen()?;
                let checked = read_manifest_bytes(root)?;
                if checked != bytes {
                    return Err(QualificationError::ManifestDrift);
                }
                println!("[stab-oracle] qualification manifest regeneration is clean");
            } else {
                let path = root.qualification_manifest();
                crate::safe_file::atomic_write_regular_file(&path, &bytes).map_err(|source| {
                    QualificationError::WriteManifest {
                        path: path.clone(),
                        reason: source.to_string().into_boxed_str(),
                    }
                })?;
                println!(
                    "[stab-oracle] wrote {} upstream cases, {} public API items, and {} evidence cases to {}",
                    generated.upstream_cases.len(),
                    generated.public_api_items.len(),
                    generated.evidence_cases.len(),
                    path.display()
                );
                println!(
                    "[stab-oracle] semantic digest {}",
                    generated.semantic_digest
                );
            }
        }
        CorrectnessCommand::ProvenanceProbe { out } => {
            run_provenance_probe(root, out)?;
        }
        CorrectnessCommand::Run {
            tier,
            feature,
            case,
            allow_deferred,
            out,
        } => {
            let checked = read_fresh_manifest(root)?;
            runner::run(
                root,
                &checked,
                runner::RunRequest {
                    tier,
                    features: feature,
                    cases: case,
                    allow_deferred,
                    output: out,
                },
            )?;
        }
        CorrectnessCommand::Report { out } => {
            let checked = read_fresh_manifest(root)?;
            let output = artifact::QualificationOutputDir::parse(root, &out)?;
            let locked = output.lock_published()?;
            let (request, request_sha256) = receipt::RunRequestReceipt::read(locked.output())?;
            let expectation =
                runner::report_expectation(root, &checked, &request, &request_sha256)?;
            report::regenerate(locked.output(), &expectation)?;
            locked.finish()?;
            println!(
                "[stab-oracle] regenerated correctness report at {}",
                output.relative().display()
            );
        }
        CorrectnessCommand::Preflight {
            out,
            case,
            request_sha256,
            completion_sha256,
            allow_dirty,
        } => {
            let checked = read_fresh_manifest(root)?;
            let output = artifact::QualificationOutputDir::parse(root, &out)?;
            let locked = output.lock_published()?;
            let (request, actual_request_sha256) =
                receipt::RunRequestReceipt::read(locked.output())?;
            if actual_request_sha256 != request_sha256 {
                return Err(QualificationError::Worker(
                    "controller-approved run-request digest is stale".into(),
                ));
            }
            let report_expectation =
                runner::report_expectation(root, &checked, &request, &request_sha256)?;
            let expected_selectors = runner::expected_selector_digests(root, &checked, &case)?;
            report::validate_preflight(
                locked.output(),
                &report_expectation,
                &report::PreflightExpectation {
                    manifest_digest: EXPECTED_FROZEN_DIGEST.to_string(),
                    run_request_sha256: request_sha256,
                    stab_commit: report_expectation.metadata.stab_commit.clone(),
                    stim_commit: checked.stim_commit.clone(),
                    selectors: expected_selectors,
                    current_worktree_dirty: report_expectation.metadata.local_modifications,
                    allow_dirty,
                    cases: case.clone(),
                },
                &completion_sha256,
            )?;
            locked.finish()?;
            println!(
                "[stab-oracle] correctness preflight passed for {} case(s)",
                case.len()
            );
        }
        CorrectnessCommand::Worker { command } => run_worker(root, command)?,
    }
    Ok(())
}

fn run_provenance_probe(root: &RepoRoot, out: PathBuf) -> Result<(), QualificationError> {
    let checked = read_fresh_manifest(root)?;
    let cases = vec![PROVENANCE_PROBE_CASE_ID.to_string()];
    runner::run(
        root,
        &checked,
        runner::RunRequest {
            tier: model::ExecutionTier::Pr,
            features: Vec::new(),
            cases: cases.clone(),
            allow_deferred: false,
            output: out.clone(),
        },
    )?;

    let output = artifact::QualificationOutputDir::parse(root, &out)?;
    let locked = output.lock_published()?;
    let (request, request_sha256) = receipt::RunRequestReceipt::read(locked.output())?;
    let report_expectation = runner::report_expectation(root, &checked, &request, &request_sha256)?;
    report::regenerate(locked.output(), &report_expectation)?;
    let qualification_report = report::QualificationReport::read(locked.output())?;
    let (execution, execution_sha256) =
        receipt::ExecutionReceipt::read(locked.output(), PROVENANCE_PROBE_CASE_ID)?;
    let (completion, completion_sha256) = receipt::RunCompletionReceipt::read(locked.output())?;

    if !request.schema_is_current()
        || !execution.schema_is_current()
        || !completion.schema_is_current()
        || request.executables != execution.executables
        || request.execution_environment_sha256 != execution.execution_environment_sha256
        || execution.run_request_sha256 != request_sha256
        || execution.verdict != receipt::ExecutionVerdict::Accepted
        || qualification_report.run_request_sha256 != request_sha256
        || qualification_report.selected_count != 1
        || qualification_report.passed_count != 1
        || qualification_report.failed_count != 0
        || request.selected_cases.len() != 1
        || qualification_report.results.len() != 1
        || completion.cases.len() != 1
    {
        return Err(QualificationError::Provenance(
            "published run metadata or provenance ledgers disagree".into(),
        ));
    }
    let selected = request.selected_cases.first().ok_or_else(|| {
        QualificationError::Provenance("published request omitted the selected case".into())
    })?;
    let result = qualification_report.results.first().ok_or_else(|| {
        QualificationError::Provenance("published report omitted the selected case".into())
    })?;
    let completed = completion.cases.first().ok_or_else(|| {
        QualificationError::Provenance("completion receipt omitted the selected case".into())
    })?;
    if selected.case_id != PROVENANCE_PROBE_CASE_ID
        || selected.selector_sha256 != execution.selector_sha256
        || result.case_id != PROVENANCE_PROBE_CASE_ID
        || result.execution_receipt_sha256 != execution_sha256
        || completed.case_id != PROVENANCE_PROBE_CASE_ID
        || completed.execution_receipt_sha256 != execution_sha256
    {
        return Err(QualificationError::Provenance(
            "published case selector or execution-receipt bindings disagree".into(),
        ));
    }

    let expected_selectors = runner::expected_selector_digests(root, &checked, &cases)?;
    report::validate_preflight(
        locked.output(),
        &report_expectation,
        &report::PreflightExpectation {
            manifest_digest: EXPECTED_FROZEN_DIGEST.to_string(),
            run_request_sha256: request_sha256.clone(),
            stab_commit: report_expectation.metadata.stab_commit.clone(),
            stim_commit: checked.stim_commit.clone(),
            selectors: expected_selectors,
            current_worktree_dirty: report_expectation.metadata.local_modifications,
            allow_dirty: true,
            cases,
        },
        &completion_sha256,
    )?;
    locked.finish()?;
    println!(
        "[stab-oracle] correctness provenance probe passed case={PROVENANCE_PROBE_CASE_ID} request_sha256={request_sha256} completion_sha256={completion_sha256} report={}",
        out.display()
    );
    Ok(())
}

fn read_fresh_manifest(root: &RepoRoot) -> Result<QualificationManifest, QualificationError> {
    ensure_frozen()?;
    let checked = read_manifest(root)?;
    validation::validate(&checked, EXPECTED_FROZEN_DIGEST)?;
    let generated = inventory::generate(root)?;
    validation::validate(&generated, EXPECTED_FROZEN_DIGEST)?;
    if checked != generated {
        return Err(QualificationError::ManifestDrift);
    }
    Ok(checked)
}

fn run_worker(root: &RepoRoot, command: WorkerCommand) -> Result<(), QualificationError> {
    let (output, property_failed) = match command {
        WorkerCommand::Fixture { id } => (
            crate::fixtures::run_qualification_core_worker(root, &id).map_err(|source| {
                QualificationError::Worker(source.to_string().into_boxed_str())
            })?,
            false,
        ),
        WorkerCommand::Property {
            id,
            plan_sha256,
            persistence_out,
            replay_in,
        } => {
            if let Some(path) = replay_in {
                let expected = property::registered_execution_plan_digest(&id)
                    .map_err(|source| QualificationError::Worker(source.into_boxed_str()))?;
                if expected != plan_sha256 {
                    return Err(QualificationError::Worker(
                        "property replay plan digest is stale".into(),
                    ));
                }
                let bytes = crate::safe_file::read_regular_file_bounded(
                    &path,
                    property::MAX_TARGET_PERSISTENCE_BYTES,
                )
                .map_err(|source| {
                    QualificationError::Worker(source.to_string().into_boxed_str())
                })?;
                property::replay_registered_failure(&id, &bytes)
                    .map_err(|source| QualificationError::Worker(source.into_boxed_str()))?;
                (
                    crate::ProcessOutput {
                        status: Some(0),
                        stdout: crate::CapturedOutput {
                            bytes: b"property regression replayed\n".to_vec(),
                            truncated: false,
                        },
                        stderr: crate::CapturedOutput {
                            bytes: Vec::new(),
                            truncated: false,
                        },
                    },
                    false,
                )
            } else {
                let mut output = property::run_registered_worker(&id, &plan_sha256)
                    .map_err(|source| QualificationError::Worker(source.into_boxed_str()))?;
                let failed = !output.success();
                if failed {
                    let path = persistence_out.ok_or_else(|| {
                        QualificationError::Worker(
                            "failing property worker has no persistence output channel".into(),
                        )
                    })?;
                    crate::safe_file::atomic_write_regular_file(&path, &output.stdout.bytes)
                        .map_err(|source| {
                            QualificationError::Worker(source.to_string().into_boxed_str())
                        })?;
                    output.stdout.bytes = b"property regression persisted\n".to_vec();
                }
                (output, failed)
            }
        }
    };
    use std::io::Write as _;
    std::io::stdout()
        .write_all(&output.stdout.bytes)
        .map_err(|source| QualificationError::Worker(source.to_string().into_boxed_str()))?;
    std::io::stderr()
        .write_all(&output.stderr.bytes)
        .map_err(|source| QualificationError::Worker(source.to_string().into_boxed_str()))?;
    if property_failed {
        return Err(QualificationError::Worker(
            "registered property target failed".into(),
        ));
    }
    Ok(())
}

fn validate_source_statistics(root: &RepoRoot) -> Result<(), QualificationError> {
    let plans = statistics::source_plan_summaries(root)
        .map_err(|source| QualificationError::Statistics(source.to_string().into_boxed_str()))?;
    statistics::validate_selected_suite(&plans)
        .map_err(|source| QualificationError::Statistics(source.to_string().into_boxed_str()))?;
    Ok(())
}

fn read_manifest(root: &RepoRoot) -> Result<QualificationManifest, QualificationError> {
    let path = root.qualification_manifest();
    let bytes = read_manifest_bytes(root)?;
    serde_json::from_slice(&bytes)
        .map_err(|source| QualificationError::ParseManifest { path, source })
}

fn read_manifest_bytes(root: &RepoRoot) -> Result<Vec<u8>, QualificationError> {
    let path = root.qualification_manifest();
    crate::safe_file::read_regular_file_bounded(&path, MAX_MANIFEST_BYTES).map_err(|source| {
        QualificationError::ReadManifest {
            path,
            reason: source.to_string().into_boxed_str(),
        }
    })
}

fn render_manifest(manifest: &QualificationManifest) -> Result<Vec<u8>, QualificationError> {
    let mut bytes =
        serde_json::to_vec_pretty(manifest).map_err(QualificationError::SerializeManifest)?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn parse_feature(value: &str) -> Result<FeatureId, QualificationError> {
    FeatureId::parse(value).ok_or_else(|| QualificationError::UnknownFeature(value.to_string()))
}

fn ensure_frozen() -> Result<(), QualificationError> {
    if EXPECTED_FROZEN_DIGEST == "UNFROZEN" {
        Err(QualificationError::UnfrozenDigest)
    } else {
        Ok(())
    }
}

fn check_existing_cargo_selectors(
    root: &RepoRoot,
    manifest: &QualificationManifest,
) -> Result<(), QualificationError> {
    let mut selectors = manifest
        .evidence_cases
        .iter()
        .filter_map(|case| {
            let selector = &case.primary_selector;
            (selector.state == model::EvidenceState::Existing
                && selector.kind == model::SelectorKind::CargoTest)
                .then(|| (case.id.to_string(), selector.value.clone()))
        })
        .collect::<Vec<_>>();
    selectors.extend(crate::fixtures::qualification_exact_cargo_selectors(root)?);
    for (owner, selector) in selectors {
        let parsed = CargoTestSelector::parse(&selector).map_err(|reason| {
            QualificationError::SelectorProcess {
                selector: format!("{owner}: {}", selector.join(" ")),
                reason: reason.into(),
            }
        })?;
        if !parsed.is_exact() {
            return Err(QualificationError::SelectorProcess {
                selector: format!("{owner}: {}", selector.join(" ")),
                reason: "selector is not exact".into(),
            });
        }
        let display = parsed.display();
        let output = crate::run_process(
            std::path::Path::new("cargo"),
            parsed.args(),
            &[],
            Some(&root.path),
        )
        .map_err(|source| QualificationError::SelectorProcess {
            selector: display.clone(),
            reason: source.to_string().into_boxed_str(),
        })?;
        if !output.success() {
            return Err(QualificationError::SelectorFailed {
                selector: display,
                status: crate::process::display_status(output.status),
                stdout: output.stdout.render_for_diagnostics().into_boxed_str(),
                stderr: output.stderr.render_for_diagnostics().into_boxed_str(),
            });
        }
        let stdout = String::from_utf8_lossy(&output.stdout.bytes);
        let actual = test_listing_match_count(&stdout);
        if actual != 1 {
            return Err(QualificationError::SelectorMatchCount {
                selector: display,
                actual,
            });
        }
    }
    Ok(())
}

fn print_summary(manifest: &QualificationManifest, selected: Option<FeatureId>) {
    let upstream = manifest
        .upstream_cases
        .iter()
        .filter(|case| selected.is_none_or(|feature| case.domain_ids.contains(&feature)))
        .collect::<Vec<_>>();
    let api = manifest
        .public_api_items
        .iter()
        .filter(|item| selected.is_none_or(|feature| item.feature_id == feature))
        .collect::<Vec<_>>();
    let evidence = manifest
        .evidence_cases
        .iter()
        .filter(|case| selected.is_none_or(|feature| case.feature_id == feature))
        .collect::<Vec<_>>();
    let mut dispositions = BTreeMap::<UpstreamDisposition, usize>::new();
    for case in &upstream {
        *dispositions.entry(case.disposition).or_default() += 1;
    }
    let mut statuses = BTreeMap::<EvidenceStatus, usize>::new();
    for case in &evidence {
        *statuses.entry(case.status).or_default() += 1;
    }
    println!(
        "[stab-oracle] qualification schema={} stim={} commit={} digest={}",
        manifest.schema_version,
        manifest.stim_version,
        manifest.stim_commit,
        manifest.semantic_digest
    );
    println!(
        "[stab-oracle] selection={} upstream={} public-api={} evidence={}",
        selected.map_or("all", FeatureId::as_str),
        upstream.len(),
        api.len(),
        evidence.len()
    );
    println!(
        "[stab-oracle] upstream exact-oracle={} ported-rust={} semantic-mining={} deferred-product={} not-applicable={} superseded={}",
        count_disposition(&dispositions, UpstreamDisposition::ExactOracle),
        count_disposition(&dispositions, UpstreamDisposition::PortedRust),
        count_disposition(&dispositions, UpstreamDisposition::SemanticMining),
        count_disposition(&dispositions, UpstreamDisposition::DeferredProduct),
        count_disposition(&dispositions, UpstreamDisposition::NotApplicable),
        count_disposition(&dispositions, UpstreamDisposition::Superseded)
    );
    println!(
        "[stab-oracle] evidence planned={} implemented={} evidence-close={} deferred={}",
        count_status(&statuses, EvidenceStatus::Planned),
        count_status(&statuses, EvidenceStatus::Implemented),
        count_status(&statuses, EvidenceStatus::EvidenceClose),
        count_status(&statuses, EvidenceStatus::Deferred)
    );
    if selected.is_none() {
        for feature in FeatureId::ALL {
            let feature_upstream = manifest
                .upstream_cases
                .iter()
                .filter(|case| case.domain_ids.contains(&feature))
                .count();
            let feature_api = manifest
                .public_api_items
                .iter()
                .filter(|item| item.feature_id == feature)
                .count();
            let feature_evidence = manifest
                .evidence_cases
                .iter()
                .filter(|case| case.feature_id == feature)
                .count();
            let feature_implemented = manifest
                .evidence_cases
                .iter()
                .filter(|case| {
                    case.feature_id == feature
                        && matches!(
                            case.status,
                            EvidenceStatus::Implemented | EvidenceStatus::EvidenceClose
                        )
                })
                .count();
            println!(
                "[stab-oracle] feature={} upstream={} public-api={} evidence={} implemented-or-closed={}",
                feature.as_str(),
                feature_upstream,
                feature_api,
                feature_evidence,
                feature_implemented
            );
        }
    }
    println!("Status: OK");
}

fn count_disposition(
    counts: &BTreeMap<UpstreamDisposition, usize>,
    disposition: UpstreamDisposition,
) -> usize {
    counts.get(&disposition).copied().unwrap_or(0)
}

fn count_status(counts: &BTreeMap<EvidenceStatus, usize>, status: EvidenceStatus) -> usize {
    counts.get(&status).copied().unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(unix)]
    #[test]
    fn qualification_manifest_reader_rejects_symlink() {
        use std::os::unix::fs::symlink;

        let temp = tempfile::tempdir().expect("temporary directory");
        let root_path = temp.path().canonicalize().expect("canonical temp path");
        let oracle_dir = root_path.join("oracle");
        std::fs::create_dir(&oracle_dir).expect("oracle directory");
        let outside = root_path.join("outside.json");
        std::fs::write(&outside, b"{}").expect("outside manifest");
        symlink(&outside, oracle_dir.join("qualification-manifest.json"))
            .expect("manifest symlink");
        let root = RepoRoot { path: root_path };
        let error = read_manifest_bytes(&root).expect_err("symlink must fail");
        assert!(matches!(error, QualificationError::ReadManifest { .. }));
    }

    #[test]
    fn large_property_regressions_use_the_dedicated_file_channel() {
        let temp = tempfile::tempdir().expect("temporary directory");
        let root = RepoRoot {
            path: temp.path().to_path_buf(),
        };
        let persistence = temp.path().join("large-regression.case");
        let id = property::LARGE_FAILURE_TARGET_ID.to_string();
        let plan_sha256 =
            property::registered_execution_plan_digest(&id).expect("large target plan");

        let error = run_worker(
            &root,
            WorkerCommand::Property {
                id: id.clone(),
                plan_sha256: plan_sha256.clone(),
                persistence_out: Some(persistence.clone()),
                replay_in: None,
            },
        )
        .expect_err("large target deliberately fails");
        assert!(matches!(error, QualificationError::Worker(_)));
        let bytes = crate::safe_file::read_regular_file_bounded(
            &persistence,
            property::MAX_TARGET_PERSISTENCE_BYTES,
        )
        .expect("large persisted regression");
        assert!(bytes.len() > crate::process::OUTPUT_LIMIT_BYTES);

        run_worker(
            &root,
            WorkerCommand::Property {
                id,
                plan_sha256,
                persistence_out: None,
                replay_in: Some(persistence),
            },
        )
        .expect("large persisted regression should replay through the worker");
    }
}
