use std::collections::BTreeMap;
use std::path::PathBuf;

use clap::Subcommand;
use thiserror::Error;

use self::model::{EvidenceStatus, FeatureId, QualificationManifest, UpstreamDisposition};
use crate::RepoRoot;
use crate::blocker_ledger::selector::{CargoTestSelector, test_listing_match_count};

mod classification;
mod extract;
mod inventory;
mod model;
mod public_api;
mod resource;
mod statistical_validation;
mod validation;

const EXPECTED_FROZEN_DIGEST: &str =
    "7b8703977838aa796f3da6bf5e6321de4491a73dfc5af2a2a07785337918abb0";
const MAX_MANIFEST_BYTES: usize = 32 << 20;

#[derive(Debug, Subcommand)]
pub(crate) enum Command {
    /// Operate on comprehensive correctness qualification evidence.
    Correctness {
        #[command(subcommand)]
        command: CorrectnessCommand,
    },
}

#[derive(Debug, Subcommand)]
pub(crate) enum CorrectnessCommand {
    /// Validate the source-owned correctness qualification inventory.
    Check,

    /// List correctness qualification coverage by feature and disposition.
    List {
        /// Restrict output to an exact feature id such as CQ-RESULT-FORMATS.
        #[arg(long)]
        feature: Option<String>,
    },

    /// Regenerate or compare the deterministic correctness inventory.
    Regenerate {
        /// Compare generated bytes with the checked-in manifest instead of writing it.
        #[arg(long)]
        check: bool,
    },
}

#[derive(Debug, Error)]
pub(crate) enum QualificationError {
    #[error(transparent)]
    BlockerLedger(#[from] crate::blocker_ledger::BlockerLedgerError),

    #[error(transparent)]
    Inventory(#[from] inventory::InventoryError),

    #[error(transparent)]
    Validation(#[from] validation::ValidationError),

    #[error("failed to read qualification manifest {path}: {reason}")]
    ReadManifest { path: PathBuf, reason: Box<str> },

    #[error("failed to parse qualification manifest {path}: {source}")]
    ParseManifest {
        path: PathBuf,
        source: serde_json::Error,
    },

    #[error("failed to serialize qualification manifest: {0}")]
    SerializeManifest(serde_json::Error),

    #[error("failed to write qualification manifest {path}: {reason}")]
    WriteManifest { path: PathBuf, reason: Box<str> },

    #[error(
        "qualification manifest differs from deterministic pinned-source regeneration; run just qualification::correctness-regenerate"
    )]
    ManifestDrift,

    #[error("unknown qualification feature {0:?}")]
    UnknownFeature(String),

    #[error("qualification inventory is not frozen in source code")]
    UnfrozenDigest,

    #[error("failed to run qualification selector {selector}: {reason}")]
    SelectorProcess { selector: String, reason: Box<str> },

    #[error(
        "qualification selector {selector} exited with {status}\nstdout:\n{stdout}\nstderr:\n{stderr}"
    )]
    SelectorFailed {
        selector: String,
        status: String,
        stdout: Box<str>,
        stderr: Box<str>,
    },

    #[error("qualification selector {selector} matched {actual} tests instead of one")]
    SelectorMatchCount { selector: String, actual: usize },
}

pub(crate) fn run(root: &RepoRoot, command: Command) -> Result<(), QualificationError> {
    let Command::Correctness { command } = command;
    match command {
        CorrectnessCommand::Check => {
            ensure_frozen()?;
            let checked = read_manifest(root)?;
            validation::validate(&checked, EXPECTED_FROZEN_DIGEST)?;
            check_existing_cargo_selectors(root, &checked)?;
            crate::blocker_ledger::validate_and_print(root, false, true)?;
            let generated = inventory::generate(root)?;
            validation::validate(&generated, EXPECTED_FROZEN_DIGEST)?;
            if checked != generated {
                return Err(QualificationError::ManifestDrift);
            }
            print_summary(&checked, None);
        }
        CorrectnessCommand::List { feature } => {
            ensure_frozen()?;
            let selected = feature.as_deref().map(parse_feature).transpose()?;
            let checked = read_manifest(root)?;
            validation::validate(&checked, EXPECTED_FROZEN_DIGEST)?;
            print_summary(&checked, selected);
        }
        CorrectnessCommand::Regenerate { check } => {
            let generated = inventory::generate(root)?;
            validation::validate(
                &generated,
                if check {
                    EXPECTED_FROZEN_DIGEST
                } else {
                    "UNFROZEN"
                },
            )?;
            let bytes = render_manifest(&generated)?;
            if check {
                ensure_frozen()?;
                let checked = read_manifest_bytes(root)?;
                if checked != bytes {
                    return Err(QualificationError::ManifestDrift);
                }
                println!("[stab-oracle] qualification manifest regeneration is clean");
            } else {
                let path = root.qualification_manifest();
                crate::safe_file::atomic_write_regular_file(&path, &bytes).map_err(|source| {
                    QualificationError::WriteManifest {
                        path: path.clone(),
                        reason: source.to_string().into_boxed_str(),
                    }
                })?;
                println!(
                    "[stab-oracle] wrote {} upstream cases, {} public API items, and {} evidence cases to {}",
                    generated.upstream_cases.len(),
                    generated.public_api_items.len(),
                    generated.evidence_cases.len(),
                    path.display()
                );
                println!(
                    "[stab-oracle] semantic digest {}",
                    generated.semantic_digest
                );
            }
        }
    }
    Ok(())
}

fn read_manifest(root: &RepoRoot) -> Result<QualificationManifest, QualificationError> {
    let path = root.qualification_manifest();
    let bytes = read_manifest_bytes(root)?;
    serde_json::from_slice(&bytes)
        .map_err(|source| QualificationError::ParseManifest { path, source })
}

fn read_manifest_bytes(root: &RepoRoot) -> Result<Vec<u8>, QualificationError> {
    let path = root.qualification_manifest();
    crate::safe_file::read_regular_file_bounded(&path, MAX_MANIFEST_BYTES).map_err(|source| {
        QualificationError::ReadManifest {
            path,
            reason: source.to_string().into_boxed_str(),
        }
    })
}

fn render_manifest(manifest: &QualificationManifest) -> Result<Vec<u8>, QualificationError> {
    let mut bytes =
        serde_json::to_vec_pretty(manifest).map_err(QualificationError::SerializeManifest)?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn parse_feature(value: &str) -> Result<FeatureId, QualificationError> {
    FeatureId::parse(value).ok_or_else(|| QualificationError::UnknownFeature(value.to_string()))
}

fn ensure_frozen() -> Result<(), QualificationError> {
    if EXPECTED_FROZEN_DIGEST == "UNFROZEN" {
        Err(QualificationError::UnfrozenDigest)
    } else {
        Ok(())
    }
}

fn check_existing_cargo_selectors(
    root: &RepoRoot,
    manifest: &QualificationManifest,
) -> Result<(), QualificationError> {
    for case in &manifest.evidence_cases {
        let selector = &case.primary_selector;
        if selector.state != model::EvidenceState::Existing
            || selector.kind != model::SelectorKind::CargoTest
        {
            continue;
        }
        let parsed = CargoTestSelector::parse(&selector.value).map_err(|reason| {
            QualificationError::SelectorProcess {
                selector: selector.value.join(" "),
                reason: reason.into(),
            }
        })?;
        let display = parsed.display();
        let output = crate::run_process(
            std::path::Path::new("cargo"),
            parsed.args(),
            &[],
            Some(&root.path),
        )
        .map_err(|source| QualificationError::SelectorProcess {
            selector: display.clone(),
            reason: source.to_string().into_boxed_str(),
        })?;
        if !output.success() {
            return Err(QualificationError::SelectorFailed {
                selector: display,
                status: crate::process::display_status(output.status),
                stdout: output.stdout.render_for_diagnostics().into_boxed_str(),
                stderr: output.stderr.render_for_diagnostics().into_boxed_str(),
            });
        }
        let stdout = String::from_utf8_lossy(&output.stdout.bytes);
        let actual = test_listing_match_count(&stdout);
        if actual != 1 {
            return Err(QualificationError::SelectorMatchCount {
                selector: display,
                actual,
            });
        }
    }
    Ok(())
}

fn print_summary(manifest: &QualificationManifest, selected: Option<FeatureId>) {
    let upstream = manifest
        .upstream_cases
        .iter()
        .filter(|case| selected.is_none_or(|feature| case.domain_ids.contains(&feature)))
        .collect::<Vec<_>>();
    let api = manifest
        .public_api_items
        .iter()
        .filter(|item| selected.is_none_or(|feature| item.feature_id == feature))
        .collect::<Vec<_>>();
    let evidence = manifest
        .evidence_cases
        .iter()
        .filter(|case| selected.is_none_or(|feature| case.feature_id == feature))
        .collect::<Vec<_>>();
    let mut dispositions = BTreeMap::<UpstreamDisposition, usize>::new();
    for case in &upstream {
        *dispositions.entry(case.disposition).or_default() += 1;
    }
    let mut statuses = BTreeMap::<EvidenceStatus, usize>::new();
    for case in &evidence {
        *statuses.entry(case.status).or_default() += 1;
    }
    println!(
        "[stab-oracle] qualification schema={} stim={} commit={} digest={}",
        manifest.schema_version,
        manifest.stim_version,
        manifest.stim_commit,
        manifest.semantic_digest
    );
    println!(
        "[stab-oracle] selection={} upstream={} public-api={} evidence={}",
        selected.map_or("all", FeatureId::as_str),
        upstream.len(),
        api.len(),
        evidence.len()
    );
    println!(
        "[stab-oracle] upstream exact-oracle={} ported-rust={} semantic-mining={} deferred-product={} not-applicable={} superseded={}",
        count_disposition(&dispositions, UpstreamDisposition::ExactOracle),
        count_disposition(&dispositions, UpstreamDisposition::PortedRust),
        count_disposition(&dispositions, UpstreamDisposition::SemanticMining),
        count_disposition(&dispositions, UpstreamDisposition::DeferredProduct),
        count_disposition(&dispositions, UpstreamDisposition::NotApplicable),
        count_disposition(&dispositions, UpstreamDisposition::Superseded)
    );
    println!(
        "[stab-oracle] evidence planned={} implemented={} evidence-close={} deferred={}",
        count_status(&statuses, EvidenceStatus::Planned),
        count_status(&statuses, EvidenceStatus::Implemented),
        count_status(&statuses, EvidenceStatus::EvidenceClose),
        count_status(&statuses, EvidenceStatus::Deferred)
    );
    if selected.is_none() {
        for feature in FeatureId::ALL {
            let feature_upstream = manifest
                .upstream_cases
                .iter()
                .filter(|case| case.domain_ids.contains(&feature))
                .count();
            let feature_api = manifest
                .public_api_items
                .iter()
                .filter(|item| item.feature_id == feature)
                .count();
            let feature_evidence = manifest
                .evidence_cases
                .iter()
                .filter(|case| case.feature_id == feature)
                .count();
            let feature_implemented = manifest
                .evidence_cases
                .iter()
                .filter(|case| {
                    case.feature_id == feature
                        && matches!(
                            case.status,
                            EvidenceStatus::Implemented | EvidenceStatus::EvidenceClose
                        )
                })
                .count();
            println!(
                "[stab-oracle] feature={} upstream={} public-api={} evidence={} implemented-or-closed={}",
                feature.as_str(),
                feature_upstream,
                feature_api,
                feature_evidence,
                feature_implemented
            );
        }
    }
    println!("Status: OK");
}

fn count_disposition(
    counts: &BTreeMap<UpstreamDisposition, usize>,
    disposition: UpstreamDisposition,
) -> usize {
    counts.get(&disposition).copied().unwrap_or(0)
}

fn count_status(counts: &BTreeMap<EvidenceStatus, usize>, status: EvidenceStatus) -> usize {
    counts.get(&status).copied().unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(unix)]
    #[test]
    fn qualification_manifest_reader_rejects_symlink() {
        use std::os::unix::fs::symlink;

        let temp = tempfile::tempdir().expect("temporary directory");
        let root_path = temp.path().canonicalize().expect("canonical temp path");
        let oracle_dir = root_path.join("oracle");
        std::fs::create_dir(&oracle_dir).expect("oracle directory");
        let outside = root_path.join("outside.json");
        std::fs::write(&outside, b"{}").expect("outside manifest");
        symlink(&outside, oracle_dir.join("qualification-manifest.json"))
            .expect("manifest symlink");
        let root = RepoRoot { path: root_path };
        let error = read_manifest_bytes(&root).expect_err("symlink must fail");
        assert!(matches!(error, QualificationError::ReadManifest { .. }));
    }
}
