mod bundle;
mod data;
mod execution;
mod host;
mod model;
mod report;
mod rust_pipeline;
mod statistics;

use std::collections::{BTreeMap, BTreeSet};
use std::fs;

use clap::Args;
use serde::Deserialize;
use sha2::{Digest as _, Sha256};

use crate::error::BenchError;
use crate::root::RepoRoot;

pub(crate) use bundle::{
    BaselineCandidateArgs, ReplayArgs, baseline_candidate, release_check, replay,
};
pub(crate) use execution::{RunArgs, WorkerArgs, run, run_worker};

#[derive(Clone, Debug, Args)]
pub(crate) struct CheckArgs {
    /// Print every release family and case after validation.
    #[arg(long)]
    list: bool,

    /// Replace the generated suite summary instead of checking it.
    #[arg(long)]
    write_docs: bool,
}

pub(crate) fn check(root: &RepoRoot, args: CheckArgs) -> Result<(), BenchError> {
    let loaded = load_suite(root)?;
    validate_prerequisites(root, &loaded.suite)?;
    check_or_write_docs(root, &loaded.suite, args.write_docs)?;
    println!(
        "[stab-bench] E2E suite schema={} families={} cases={} digest={}",
        loaded.suite.schema_version,
        loaded.suite.families.len(),
        loaded.suite.case_count(),
        loaded.digest
    );
    if args.list {
        for family in &loaded.suite.families {
            for case in &family.cases {
                println!("{}.{}", family.id, case.id);
            }
        }
    }
    Ok(())
}

fn check_or_write_docs(
    root: &RepoRoot,
    suite: &model::Suite,
    write_docs: bool,
) -> Result<(), BenchError> {
    let path = root.e2e_suite_doc();
    let expected = render_suite(suite);
    if write_docs {
        fs::write(&path, expected).map_err(|source| {
            BenchError::E2e(format!("failed to write {}: {source}", path.display()))
        })?;
        return Ok(());
    }
    let actual = fs::read_to_string(&path).map_err(|source| {
        BenchError::E2e(format!(
            "failed to read generated {}: {source}; run just bench::e2e-check --write-docs",
            path.display()
        ))
    })?;
    if actual != expected {
        return Err(BenchError::E2e(format!(
            "{} is stale; run just bench::e2e-check --write-docs",
            path.display()
        )));
    }
    Ok(())
}

fn render_suite(suite: &model::Suite) -> String {
    let mut text = String::from(
        "<!-- Generated by `just bench::e2e-check --write-docs`; do not edit. -->\n\n# E2E Performance Suite\n\n",
    );
    text.push_str(&format!(
        "Timing boundary: `{}`. Stim parity requires median and confidence upper bound `<= {:.2}x`. Seeded Stab self-regression requires both `<= {:.2}x`.\n",
        suite.policy.timing_boundary,
        suite.policy.parity_max_ratio,
        suite.policy.self_regression_max_ratio
    ));
    text.push_str("| Family | Case | Boundary | Comparator | Size | Semantic work | Batch | Stab RSS limit |\n| --- | --- | --- | --- | --- | ---: | ---: | ---: |\n");
    for family in &suite.families {
        for case in &family.cases {
            text.push_str(&format!(
                "| `{}` | `{}` | `{}` | `{}` | `{:?}` | {} `{}` | {} | {} MiB |",
                family.id,
                case.id,
                runner_name(family.runner),
                comparator_name(family.comparator),
                case.size_class,
                case.work.amount,
                work_unit_name(case.work.unit),
                case.batch,
                case.maximum_stab_peak_rss_bytes / (1 << 20),
            ));
            text.push('\n');
        }
    }
    text.push_str("\n## Correctness Prerequisites\n\n");
    for family in &suite.families {
        text.push_str(&format!(
            "- `{}`: {}",
            family.id,
            family
                .prerequisites
                .iter()
                .map(|item| format!("`{item}`"))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        text.push('\n');
    }
    text.push_str(&format!(
        "\nAccepted self-regression baselines: {}.\n",
        suite.self_baselines.len(),
    ));
    text
}

const fn runner_name(runner: model::RunnerKind) -> &'static str {
    match runner {
        model::RunnerKind::Cli => "CLI process",
        model::RunnerKind::Rust => "Rust API",
    }
}

const fn comparator_name(comparator: model::Comparator) -> &'static str {
    match comparator {
        model::Comparator::StimCli => "Stim CLI",
        model::Comparator::SelfOnly => "Stab baseline",
    }
}

const fn work_unit_name(unit: model::WorkUnit) -> &'static str {
    match unit {
        model::WorkUnit::GeneratedBytes => "generated bytes",
        model::WorkUnit::InputBytes => "input bytes",
        model::WorkUnit::Records => "records",
        model::WorkUnit::Shots => "shots",
    }
}

struct LoadedSuite {
    bytes: Vec<u8>,
    digest: String,
    suite: model::Suite,
}

fn load_suite(root: &RepoRoot) -> Result<LoadedSuite, BenchError> {
    let path = root.e2e_suite();
    let bytes = fs::read(&path).map_err(|source| {
        BenchError::E2e(format!("failed to read {}: {source}", path.display()))
    })?;
    let suite = toml::from_slice::<model::Suite>(&bytes).map_err(|source| {
        BenchError::E2e(format!("failed to parse {}: {source}", path.display()))
    })?;
    suite.validate().map_err(BenchError::E2e)?;
    let digest = hex::encode(Sha256::digest(&bytes));
    Ok(LoadedSuite {
        bytes,
        digest,
        suite,
    })
}

fn validate_prerequisites(root: &RepoRoot, suite: &model::Suite) -> Result<(), BenchError> {
    let root_path = root.path.join("oracle").join("stim-v1.16-parity.toml");
    let root_bytes = fs::read(&root_path).map_err(|source| {
        BenchError::E2e(format!("failed to read {}: {source}", root_path.display()))
    })?;
    let manifest = toml::from_slice::<ParityRoot>(&root_bytes).map_err(|source| {
        BenchError::E2e(format!("failed to parse {}: {source}", root_path.display()))
    })?;
    let mut statuses = BTreeMap::new();
    for relative in manifest.family_files {
        let path = root.path.join(relative);
        let bytes = fs::read(&path).map_err(|source| {
            BenchError::E2e(format!("failed to read {}: {source}", path.display()))
        })?;
        let fragment = toml::from_slice::<ParityFragment>(&bytes).map_err(|source| {
            BenchError::E2e(format!("failed to parse {}: {source}", path.display()))
        })?;
        for family in fragment.families {
            if statuses.insert(family.id.clone(), family.status).is_some() {
                return Err(BenchError::E2e(format!(
                    "duplicate parity family {}",
                    family.id
                )));
            }
        }
    }
    let required = suite
        .families
        .iter()
        .flat_map(|family| family.prerequisites.iter())
        .collect::<BTreeSet<_>>();
    let mut errors = Vec::new();
    for prerequisite in required {
        match statuses.get(prerequisite) {
            Some(status) if status == "done" || status == "divergence" => {}
            Some(status) => errors.push(format!(
                "correctness prerequisite {prerequisite} has status {status}"
            )),
            None => errors.push(format!(
                "correctness prerequisite {prerequisite} is not in the parity ledger"
            )),
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        Err(BenchError::E2e(errors.join("\n")))
    }
}

#[derive(Deserialize)]
struct ParityRoot {
    family_files: Vec<String>,
}

#[derive(Deserialize)]
struct ParityFragment {
    families: Vec<ParityFamily>,
}

#[derive(Deserialize)]
struct ParityFamily {
    id: String,
    status: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checked_suite_has_the_frozen_release_shape() {
        let root = RepoRoot::resolve(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../..")
                .as_path(),
        )
        .expect("repo root");
        let loaded = load_suite(&root).expect("checked suite");
        validate_prerequisites(&root, &loaded.suite).expect("done prerequisites");
        assert_eq!(loaded.suite.families.len(), 12);
        assert_eq!(loaded.suite.case_count(), 29);
    }
}
